project/api_v1/urls.py
from django.urls import path, reverse_lazy, include

from .views import (GeoLocationGetView, GeoLocationDeleteView, GeoLocationCreateView, GeoLocationUpdateView)
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
		path('get/<int:pk>/', GeoLocationGetView.as_view()),
		path('delete/<int:pk>/', GeoLocationDeleteView.as_view()),
		path('create/', GeoLocationCreateView.as_view()),
		path('update/<int:pk>/', GeoLocationUpdateView.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

project/geo_loc/urls.py
from django.urls import path, reverse_lazy, include

from .views import (GeoLocListView, GeoLocRegisterCreateView,
					 GeoLocLoginView, GeoLocLogoutView,
					 GeoLocLookUpCreateView, GeoLocDeleteView,
					 GeoLocUpdateView
					 )
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
		path('index/', GeoLocListView.as_view(), name='geo-loc-l_view'),
		path('index/lookup/', GeoLocLookUpCreateView.as_view(), name='geo-loc-lu_view'),
		path('register/', GeoLocRegisterCreateView.as_view(), name='geo-loc-c_view'),
		path('login/', GeoLocLoginView.as_view(), name='geo-loc-login_view'),
		path('logout/', GeoLocLogoutView.as_view(), name='geo-loc-logout_view'),
		# CRUD
		path('index/delete/<pk>', GeoLocDeleteView.as_view(), name='geo-loc-delete_view'),
		path('index/update/<pk>', GeoLocUpdateView.as_view(), name='geo-loc-update_view'),
		# REST
		path('api/v1/', include(('api_v1.urls', 'api_v1'), namespace='apiv1')),
		# JWT
		path('token/obtain/', TokenObtainPairView.as_view(), name='obtain-new-token'),
		path('token/refresh/', TokenRefreshView.as_view(), name='refresh-token'),
		path('token/verify/', TokenVerifyView.as_view(), name='verify-token'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('geoloc/', include(('geo_loc.urls', 'geoloc'), namespace='geoloc')),
    path('', RedirectView.as_view(url=reverse_lazy('geoloc:geo-loc-l_view')))
]

project/geo_loc/models.py
from django.db import models
from django.contrib.auth.models import User

class Region(models.Model):
	continent_name = models.CharField(max_length=50, unique=False)
	continent_code = models.CharField(max_length=50, unique=False)
	country_name = models.CharField(max_length=50, unique=False)
	country_code = models.CharField(max_length=50, unique=False)
	city = models.CharField(max_length=50, unique=False)
	zip_number = models.CharField(max_length=10, unique=False)

	def __str__(self):
		return f'{self.city}'


class Geo_Loc(models.Model):
	ip = models.CharField(max_length=50, unique=False)
	protocol = models.CharField(max_length=50, unique=False)
	region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True, blank=True, related_name="geo_loc_region")
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="geo_loc_user")

	def __str__(self):
		return f'{self.ip} {self.protocol}'

project/geo_loc/forms.py
from django import forms

from .models import Geo_Loc, Region

from django.contrib.auth.models import User


class GeoLocUser_Registration(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'password']

		widgets = {
				'password': forms.PasswordInput(),
		}

class GeoLocLookUpData(forms.ModelForm):
	class Meta:
		model = Geo_Loc
		fields = ['ip', 'protocol', 'region']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

class RegionLookUpData(forms.ModelForm):
	class Meta:
		model = Region
		fields = ['continent_name',
				  'continent_code',
				  'country_name',
				  'country_code',
				  'city',
				  'zip_number',]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

project/geo_loc/views.py
from django.views.generic.edit import (CreateView, DeleteView,
										UpdateView)
from django.shortcuts import render, get_object_or_404, Http404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.list import ListView
from .models import Geo_Loc, Region
from .geoapi import GeoApi
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import authenticate, login
from django.http import HttpResponseNotFound
from django.views.generic.base import RedirectView
from django.contrib.auth.forms import UserCreationForm
from .forms import (GeoLocUser_Registration, GeoLocLookUpData,
					RegionLookUpData)

class GeoLocRegisterCreateView(CreateView):
	model = User
	form_class = UserCreationForm
	
	def post(self, *args, **kwargs):
		super().post(*args, **kwargs)
		user = authenticate(username=self.request.POST['username'],
		 password=self.request.POST['password1'])
		if user is not None or 'AnonymousUser':
			login(self.request, user)
			return HttpResponseRedirect(reverse('geoloc:geo-loc-l_view'))
		return HttpResponseRedirect(reverse('geoloc:geo-loc-c_view'))

	def get_success_url(self):
		pk = self.object.id
		post_instance = get_object_or_404(User, pk=pk)
		return reverse('geoloc:geo-loc-l_view')

class GeoLocUpdateView(UpdateView):
	model = Region
	success_url = reverse_lazy('geoloc:geo-loc-l_view')
	fields = ['continent_name',
		  'continent_code',
		  'country_name',
		  'country_code',
		  'city',
		  'zip_number',]

class GeoLocDeleteView(DeleteView):
	model = Geo_Loc
	success_url = reverse_lazy('geoloc:geo-loc-l_view')

class GeoLocLookUpCreateView(CreateView):
	model = Geo_Loc

	def post(self, *args, **kwargs):
		key = settings.GEO_ACCESS_KEY
		g_api  = GeoApi(key)
		geo_locations_data = g_api.get_location(self.request.POST['geo_ip'])

		form = GeoLocLookUpData(geo_locations_data)
		form_region = RegionLookUpData(geo_locations_data.pop('region'))

		if form.is_valid() and form_region.is_valid():
			geo_loc_data = form.save()
			form_geo_data = form_region.save()
			geo_loc_data.user = self.request.user
			geo_loc_data.region = form_geo_data
			geo_loc_data.save()
			form_geo_data.save()
			return HttpResponseRedirect(reverse('geoloc:geo-loc-l_view'))
		raise Http404('Form validation was not possible.')

	def get_success_url(self):
		pk = self.object.id
		post_instance = get_object_or_404(User, pk=pk)
		return reverse('geoloc:geo-loc-l_view')


class GeoLocListView(LoginRequiredMixin, ListView):
	model = Geo_Loc
	paginate_by = 5

	def post(self, request, *args, **kwargs):
	    self.object_list = self.get_queryset()
	    allow_empty = self.get_allow_empty()

	    if not allow_empty:
	        if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
	            is_empty = not self.object_list.exists()
	        else:
	            is_empty = not self.object_list
	        if is_empty:
	            raise Http404(_('Empty list and “%(class_name)s.allow_empty” is False.') % {
	                'class_name': self.__class__.__name__,
	            })
	    context = self.get_context_data()
	    return self.render_to_response(context)

	def get_context_data(self, *, object_list=None, **kwargs):
		queryset = object_list if object_list is not None else self.object_list
		return super().get_context_data(
            object_list=queryset.filter(user=self.request.user),
            geo_ip_lookup=self.request.POST['geo_ip'] if "geo_ip" in self.request.POST
             else self.request.META.get("REMOTE_ADDR"),
            **kwargs)


class GeoLocLoginView(LoginView):
	model = User

	def get_succes_url(self):
		return reverse("geoloc:geo-loc-l_view")

class GeoLocLogoutView(LogoutView):
	model = User

project/geo_loc/templates/geo_loc/geo_loc_list.html
{% extends "base.html" %}

{% block content %}


<section>

<h1> Logged as: {{ request.user }}</h1>
</section>

<div class="geo-loc-div-tbl-1">

<table class="geo-loc-tbl-1 table table-borderless table-hover" style="background-color: rgba(0,0,110, 0.1);">
	<thead>
		<tr>
			<th scope="col">IP</th>
			<th scope="col">Protocol</th>
			<th scope="col">Continent name</th>
			<th scope="col">Continent code</th>
			<th scope="col">Country name</th>
			<th scope="col">Country code</th>
			<th scope="col">City</th>
			<th scope="col">Zip</th>
			<th scope="col">Operation</th>
		</tr>
	</thead>
	{% for obj in object_list %}
	<tr>
		<td> {{ obj.ip }} </td>
		<td> {{ obj.protocol }} </td>
		<td> {{ obj.region.continent_name }} </td>
		<td> {{ obj.region.continent_code }} </td>
		<td> {{ obj.region.country_name }} </td>
		<td> {{ obj.region.country_code }} </td>
		<td> {{ obj.region.city }} </td>
		<td> {{ obj.region.zip_number }} </td>
		<td>  
			<a href="{% url 'geoloc:geo-loc-update_view' obj.region.id %}"> <input type="button" value="U" class="btn-neutral">  </a> 
			<form method="POST" action="{% url 'geoloc:geo-loc-delete_view' obj.id %}">
				{% csrf_token %}
				<input class="btn-alert" type="submit" value="D">
			</form>  
		</td>
	</tr>
{% empty %}
	<br>
	<tr>
		<td colspan="6">no items</td>
	</tr>
{% endfor %}
</tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


</div>

</div>
<div class="geo-loc-form_1" style="padding: 20px; text-align: center; color: white;"> 
	<p>IP Geolocation </p>

	<form method="post" action=" {% url 'geoloc:geo-loc-lu_view' %}">{% csrf_token %}
		<input style="padding: 10px; background-color: rgba(11,155,15, 0.5)" type="text" class="btn-sucess" name="geo_ip" value="{{ geo_ip_lookup }}">
		<input style="background-color: rgba(11,155,15, 0.5)" type="submit" class="btn-sucess" value="Look up">
	</form>

</div>



{% endblock %}

project/geo_loc/templates/geo_loc/region_form.html
{% extends "base.html" %}

{% block content %}
<section>
	<div class="geo-loc-form_2">
	<b>Update view</b> for <b>{{ object }}</b> no. <b> {{ object.id }} </b> 
		<form method="post">{% csrf_token %}
			{{ form.as_p }}
    		<input type="submit" class="btn-sucess" style="width: 50%; left: 20%; position: relative; margin-top: 5px;" value="Confirm">
		</form>
	</div>
</section>

{% endblock %}

project/geo_loc/templates/geo_loc/user_form.html
{% extends "base.html" %}

{% block content %}
<section>
	<div class="geo-loc-form_2">
		<form method="post">{% csrf_token %}
    		{{ form.as_p }}
            <input class="btn-sucess" type="submit" style="width: 50%; left: 20%; position: relative; margin-top: 5px;" value="Save">
		</form>
</section>
</div>
{% endblock %}